node {
    stage('Build') {
        docker.image('python:3-alpine').inside {
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            stash(name: 'compiled-results', includes: 'sources/*.py*')
        }
    }
    stage('Test') {
        docker.image('qnib/pytest').inside {
            sh 'py.test --junit-xml test-reports/results.xml sources/test_calc.py'
        }
        try {
            junit 'test-reports/results.xml'
        } catch (Exception e) {
            echo 'Error: ' + e.toString()
        }
    }
    stage('Manual Approval') {
    script {
        def userInput = input(
            message: 'Lanjutkan ke tahap Deploy?',
            parameters: [
                [$class: 'ChoiceParameter', name: 'approval', choices: 'Proceed\nAbort', description: 'Select your choice']
            ],
            submitter: 'user'
        )
        if (userInput.approval == 'Abort') {
            error('Deployment aborted by user')
        }
    }
}
    stage('Deploy') {
        node('any') {
            stage('Prepare') {
                unstash(name: 'compiled-results')
                sleep(60)
                echo "Please regularly check http://13.229.182.106/ for updates."
                // deployment-stage Jenkins project is triggered
                // uploading the unstashed file to the EC2 instance
                // after this stage is completed

                // configuration of new project with Publish Over SSH plugin
                // will be shown, please note!
            }
        }
    }
}
