node {
    stage('Build') {
        docker.image('python:2-alpine').inside {
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            stash(name: 'compiled-results', includes: 'sources/*.py*')
        }
    }

    stage('Test') {
        docker.image('qnib/pytest').inside {
            try {
                sh 'py.test --junit-xml test-reports/results.xml sources/test_calc.py'
            } catch (Exception e) {
                echo 'Error: ' + e.toString()
            } finally {
                junit 'test-reports/results.xml'
            }
        }
    }

    stage('Deliver') {
        def VOLUME = "${workspace}/sources:/src"
        def IMAGE = 'cdrx/pyinstaller-linux:python2'
        
        docker.image(IMAGE).inside("-v ${VOLUME}") {
            try {
                dir("${BUILD_ID}") {
                    unstash(name: 'compiled-results')
                    sh "pyinstaller --onefile sources/add2vals.py"
                }
            } catch (Exception e) {
                echo 'Error: ' + e.toString()
            } finally {
                success {
                    archiveArtifacts 'dist/add2vals'
                }
                sh "rm -rf build dist"
            }
        }
    }
}